import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Origo",
  description: "Origo terms of service and conditions of use.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-300">
      <div className="mx-auto max-w-3xl px-6 py-20">
        <Link href="/" className="text-sm text-violet-400 hover:text-violet-300 transition-colors">
          &larr; Back to Home
        </Link>

        <h1 className="mt-8 text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: May 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Origo (&quot;the Service&quot;), operated by Sandnes Productions,
              you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Origo is an AI-powered code generation platform. You provide project specifications
              through a questionnaire, and Origo generates source code files that you can download
              as a ZIP archive. Generated code is provided as-is and is intended as a starting point
              for further development.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Credits and Payments</h2>
            <p>
              Project generation requires credits. Credits are purchased through our payment
              provider (Stripe) and are non-refundable except where required by applicable law.
              If a generation fails due to a system error, the credit will be automatically refunded
              to your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Ownership of Generated Code</h2>
            <p>
              You own the code generated by Origo for your projects. You may use, modify, and
              distribute the generated code without restriction. Origo does not claim any
              intellectual property rights over generated output.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use the Service to generate malicious software, malware, or exploits</li>
              <li>Attempt to circumvent rate limits, credit systems, or security measures</li>
              <li>Resell generated projects as an automated competing service</li>
              <li>Share your account credentials with others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. Generated
              code may contain bugs, security issues, or incompatibilities. You are responsible
              for reviewing, testing, and securing any code before deploying it to production.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Sandnes Productions shall not be liable for
              any indirect, incidental, special, consequential, or punitive damages arising from
              your use of the Service or any generated code.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after
              changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:flemmingravndal@hotmail.com" className="text-violet-400 hover:text-violet-300">
                flemmingravndal@hotmail.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
