"use client";

import type { SimulationReport } from "@/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getRiskBadgeClass, formatCurrency } from "@/lib/utils";
import { AgentAvatar } from "@/components/agents/AgentAvatar";
import type { AgentRole } from "@/types";
import {
  AlertTriangle,
  CheckCircle,
  TrendingUp,
  Clock,
  DollarSign,
  Download,
  Lightbulb,
} from "lucide-react";

interface RiskReportProps {
  report: SimulationReport;
  projectBudget?: number;
  projectTimeline?: number;
}

const priorityOrder = { high: 0, medium: 1, low: 2 };

export function RiskReport({
  report,
  projectBudget,
  projectTimeline,
}: RiskReportProps) {
  const sortedRisks = [...report.risks].sort(
    (a, b) =>
      (b.likelihood * b.impact) - (a.likelihood * a.impact)
  );

  const sortedRecommendations = [...report.recommendations].sort(
    (a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]
  );

  const successColor =
    report.success_probability >= 70
      ? "text-emerald-600"
      : report.success_probability >= 50
      ? "text-amber-600"
      : "text-red-600";

  return (
    <div className="space-y-6">
      {/* Executive Summary */}
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <CardTitle className="text-xl">Post-Simulation Risk Report</CardTitle>
              <p className="text-sm text-zinc-500 mt-1">
                Generated by FlowForge multi-agent simulation
              </p>
            </div>
            <Button variant="outline" size="sm">
              <Download className="w-4 h-4" />
              Export PDF
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-zinc-700 leading-relaxed mb-6">
            {report.executive_summary}
          </p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="text-center p-4 bg-zinc-50 rounded-xl">
              <div className={`text-3xl font-bold ${successColor}`}>
                {report.success_probability}%
              </div>
              <div className="text-xs text-zinc-500 mt-1">Success Probability</div>
            </div>
            <div className="text-center p-4 bg-zinc-50 rounded-xl">
              <div className="text-3xl font-bold text-zinc-900">
                {report.risks.length}
              </div>
              <div className="text-xs text-zinc-500 mt-1">Risks Identified</div>
            </div>
            {projectTimeline && (
              <div className="text-center p-4 bg-zinc-50 rounded-xl">
                <div className="flex items-center justify-center gap-1">
                  <Clock className="w-4 h-4 text-zinc-400" />
                  <div className="text-2xl font-bold text-zinc-900">
                    {report.revised_timeline_weeks}w
                  </div>
                </div>
                <div className="text-xs text-zinc-500 mt-1">
                  Revised Timeline{" "}
                  {report.revised_timeline_weeks > projectTimeline && (
                    <span className="text-amber-600">
                      (+{report.revised_timeline_weeks - projectTimeline}w)
                    </span>
                  )}
                </div>
              </div>
            )}
            {projectBudget && (
              <div className="text-center p-4 bg-zinc-50 rounded-xl">
                <div className="flex items-center justify-center gap-1">
                  <DollarSign className="w-4 h-4 text-zinc-400" />
                  <div className="text-2xl font-bold text-zinc-900">
                    {report.revised_budget_multiplier.toFixed(1)}x
                  </div>
                </div>
                <div className="text-xs text-zinc-500 mt-1">
                  Budget Multiplier
                  {report.revised_budget_multiplier > 1 && (
                    <span className="block text-amber-600">
                      ~{formatCurrency(projectBudget * report.revised_budget_multiplier)}
                    </span>
                  )}
                </div>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Risk Matrix */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-500" />
            Identified Risks
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {sortedRisks.map((risk) => (
              <div
                key={risk.id}
                className="p-4 rounded-xl border border-zinc-200 hover:border-zinc-300 transition-colors"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-semibold text-sm text-zinc-900">
                        {risk.title}
                      </span>
                      <span
                        className={`text-xs px-2 py-0.5 rounded-full font-medium ${getRiskBadgeClass(
                          risk.level
                        )}`}
                      >
                        {risk.level.toUpperCase()}
                      </span>
                      <span className="text-xs text-zinc-400 bg-zinc-100 px-2 py-0.5 rounded-full">
                        {risk.category.replace(/_/g, " ")}
                      </span>
                    </div>
                    <p className="text-sm text-zinc-600 mb-2">{risk.description}</p>
                    <div className="flex items-start gap-1 text-sm">
                      <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0 mt-0.5" />
                      <span className="text-emerald-700">{risk.mitigation}</span>
                    </div>
                  </div>
                  <div className="text-right text-xs text-zinc-400 flex-shrink-0">
                    <div>Likelihood: <span className="font-semibold text-zinc-700">{risk.likelihood}%</span></div>
                    <div>Impact: <span className="font-semibold text-zinc-700">{risk.impact}%</span></div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Recommendations */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-indigo-500" />
            Recommendations
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {sortedRecommendations.map((rec, i) => (
              <div
                key={i}
                className="p-4 rounded-xl border border-zinc-200 flex gap-3"
              >
                <div
                  className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5 ${
                    rec.priority === "high"
                      ? "bg-red-100 text-red-700"
                      : rec.priority === "medium"
                      ? "bg-amber-100 text-amber-700"
                      : "bg-zinc-100 text-zinc-600"
                  }`}
                >
                  {i + 1}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-semibold text-sm text-zinc-900">
                      {rec.title}
                    </span>
                    <span className="text-xs text-zinc-400">
                      Effort: {rec.effort}
                    </span>
                  </div>
                  <p className="text-sm text-zinc-600">{rec.description}</p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Process Improvements */}
      {report.process_improvements.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-emerald-500" />
              Process Improvements
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {report.process_improvements.map((improvement, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-zinc-700">
                  <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0 mt-0.5" />
                  {improvement}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Agent Performance */}
      {report.agent_performance.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Agent Contributions</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
              {report.agent_performance.map((perf) => (
                <div
                  key={perf.role}
                  className="p-3 rounded-xl border border-zinc-200 text-center"
                >
                  <AgentAvatar
                    role={perf.role as AgentRole}
                    size="md"
                    className="justify-center mb-2"
                  />
                  <div className="text-xs text-zinc-500">
                    {perf.concerns_raised} concerns
                  </div>
                  <div className="text-xs text-zinc-500">
                    {perf.conflicts_involved} conflicts
                  </div>
                  <div className="mt-1 text-sm font-semibold text-zinc-900">
                    {perf.effectiveness_score}%
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
